image: registry.gitlab.com/materials-modeling/icet:latest


build_linux:
  stage: build
  tags:
    - linux
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    expire_in: 14 days
    paths:
      - build


tests:
  stage: test
  tags:
    - linux
  dependencies:
    - build_linux
  script:
    - export PATH=${PATH}:${HOME}/.local/bin
    - export PYTHONPATH=$PWD:$PWD/build/src/:$PYTHONPATH
    - coverage run tests/__init__.py
    - coverage report -m
    - coverage html -d coverage
    - for f in benchmark/*.py; do python3 "$f"; done
    - for f in examples/*.py; do python3 "$f"; done
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    expire_in: 14 days
    paths:
      - coverage/


style_check:
  stage: test
  tags:
    - linux
  script:
    - cd tests/
    - python3 check_flake8__.py
  allow_failure: true


pages:
  stage: deploy
  dependencies:
    - build_linux
    - tests
  script:
    # homepage
    - wget https://github.com/jasonlong/cayman-theme/archive/master.zip
    - unzip master.zip
    - mv cayman-theme-master public/
    - cp doc/homepage/index.html public/
    - cp doc/homepage/robots.txt public/
    # doxygen
    - cd doc/apidoc/
    - doxygen Doxyfile
    - cd ../..
    # sphinx
    - pip3 install breathe
    - export PYTHONPATH=$PWD:$PWD/build/src/:$PYTHONPATH
    - sphinx-build doc/userguide/source/ public/userguide/
    # consolidate
    - mv doc/apidoc/html/ public/apidoc/
    - mv coverage/ public/
    # letsencrypt setup
    - fname=`awk '{split($0, s, "."); print s[1]}' doc/homepage/letsencrypt-setup.html`
    - mkdir -p public/.well-known/acme-challenge/
    - mv doc/homepage/letsencrypt-setup.html public/.well-known/acme-challenge/$fname
    - ls -l public/.well-known/acme-challenge/
  artifacts:
    expire_in: 30 days
    paths:
      - public
  only:
    - master
