image: registry.gitlab.com/icet/icet-dev:latest


build_linux:
  stage: build
  tags:
    - linux
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build


run_tests:
  stage: test
  tags:
    - linux
  dependencies:
    - build_linux
  script:
    - export PYTHONPATH=/builds/icet/icet-dev:$PYTHONPATH
    - export PYTHONPATH=/builds/icet/icet-dev/build/src/:$PYTHONPATH
    - python3 tests/__init__.py


coverage:
  stage: test
  tags:
    - linux
  dependencies:
    - build_linux
  script:
    - export PYTHONPATH=/builds/icet/icet-dev:$PYTHONPATH
    - export PYTHONPATH=/builds/icet/icet-dev/build/src/:$PYTHONPATH
    - pip3 install coverage
    - coverage run tests/__init__.py
    - coverage report -m
    - coverage html -d coverage
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    name: coverage
    expire_in: 15 days
    paths:
      - coverage/


pages:
  stage: deploy
  dependencies:
    - coverage
  script:
    - mv public/ .public/ || true
    - mkdir public/ || true
    - mkdir public/coverage || true
    - mv coverage/index.html public/coverage/ || true
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
