image: registry.gitlab.com/materials-modeling/icet:latest


build_linux:
  stage: build
  tags:
    - linux
  script:
    - mkdir build
    - cd build
    - python3 -m pip install .. -t . -v --no-cache-dir
  artifacts:
    expire_in: 14 days
    paths:
      - build


tests:
  stage: test
  tags:
    - linux
  dependencies:
    - build_linux
  script:
    - export PYTHONPATH=$PWD:$PWD/build/:$PYTHONPATH
    - coverage run tests/main.py
    - coverage report -m
    - coverage html -d coverage
    - for f in benchmark/*.py; do python3 "$f"; done
    - for f in $(ls tutorial/advanced/*.py | grep -v parallel_monte_carlo.py); do echo $f ; python3 $f >/dev/null; done
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    expire_in: 14 days
    paths:
      - coverage/


test_benchmarks_tutorial:
  stage: test
  only:
    - schedules
  tags:
    - linux
  dependencies:
    - build_linux
  script:
    - export PYTHONPATH=$PWD:$PWD/build/:$PYTHONPATH
    - for f in benchmark/*.py; do echo $f ; python3 $f ; done
    - for f in $(ls tutorial/*/*.py | grep -v parallel_monte_carlo.py); do echo $f ; python3 $f ; done


style_check:
  stage: test
  tags:
    - linux
  script:
    - python3 tests/check_flake8__.py
  allow_failure: true


pages:
  stage: deploy
  dependencies:
    - build_linux
    - tests
  script:
    # prepare homepage
    - mkdir public
    # coverage report
    - mv coverage/ public/
    # letsencrypt setup
    - fname=`awk '{split($0, s, "."); print s[1]}' doc/letsencrypt-setup.html`
    - mkdir -p public/.well-known/acme-challenge/
    - mv doc/letsencrypt-setup.html public/.well-known/acme-challenge/$fname
    # C++ documentation (doxygen)
    - cd doc/apidoc/
    - doxygen Doxyfile
    - cd ../..
    - mv doc/apidoc/html/ public/apidoc/
    # user guide (sphinx)
    - export PYTHONPATH=$PWD:$PWD/build/:$PYTHONPATH
    - sphinx-build doc/userguide/source/ public/
    # make tests and tutorial downloadable
    - zip -rj public/basic_tutorial.zip tutorial/basic/
    - zip -rj public/advanced_tutorial.zip tutorial/advanced/
    - find tests/ -name '*.py' -print | zip public/tests.zip tests/structure_databases/*.db -@
    # clean up
    - ls -l public/.well-known/acme-challenge/
    - ls -l public/
    - chmod go-rwX -R public/
  artifacts:
    expire_in: 30 days
    paths:
      - public
  only:
    - master
