image: ubuntu:latest

before_script:
  - apt-get -yqq update
  - apt-get -yqq install cmake
                         git
                         build-essential
                         libboost-all-dev
                         libeigen3-dev
                         libboost-system-dev
                         libboost-thread-dev
                         libboost-filesystem-dev
                         python3-dev
                         python-dev
                         python3-numpy
                         python-numpy
                         python3-pip
                         python3-sphinx
                         python-sphinx
                         python3-joblib
                         python-joblib
                         python
                         libgsl-dev
                         python-tk
                         python3-coverage
                         pylint3
  - pip3 install --upgrade --user ase
  - pip3 install --upgrade --user spglib
  
  

build_linux:
  stage: build
  tags:
    - linux
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
      paths:
        - build

run_tests:
  stage: test
  tags:
    - linux
  dependencies:
    - build_linux
  script:
    - mkdir $PWD/code_analysis
    - export PYTHONPATH=/builds/icet/icet-dev:$PYTHONPATH
    - export PYTHONPATH=/builds/icet/icet-dev/build/src/:$PYTHONPATH
    - echo $PWD 
    - echo $PYTHONPATH
    - ls -l
    - bash .run_code_analysis.sh
    - python3-coverage run tests/__init__.py
    - python3-coverage html -d py_coverage
    - cp -r py_coverage $PWD/code_analysis/
    - cp .pylint_score $PWD/code_analysis/
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  artifacts:
    name: py_coverage
    expire_in: 30 days 
    paths:      
      - code_analysis/

pages:
  stage: deploy
  dependencies:
    - run_tests
  script:
    - mv public/ .public/ || true
    - mkdir public/ || true    
    - mkdir public/pylint
    - mv code_analysis/py_coverage/ public/ || true
    - mv code_analysis/.pylint_score public/pylint/ || true
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master

