image: ubuntu:latest

before_script:
  - apt-get -yqq update
  - apt-get -yqq install cmake
                         git
                         build-essential
                         libboost-all-dev
                         libeigen3-dev
                         libboost-system-dev
                         libboost-thread-dev
                         libboost-filesystem-dev
                         python3-dev
                         python-dev
                         python3-numpy
                         python-numpy
                         python3-pip
                         python3-sphinx
                         python-sphinx
                         python3-joblib
                         python-joblib
                         python
                         libgsl-dev
                         python-tk
                         python3-coverage
                         pylint3
  - pip3 install --upgrade --user ase
  - pip3 install --upgrade --user spglib
  
  

build_linux:
  stage: build
  tags:
    - linux
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
      paths:
        - build

run_tests:
  stage: test
  tags:
    - linux
  dependencies:
    - build_linux
  script:
    - export PYTHONPATH=/builds/icet/icet-dev:$PYTHONPATH
    - export PYTHONPATH=/builds/icet/icet-dev/build/src/:$PYTHONPATH
    - echo $PWD 
    - echo $PYTHONPATH
    - python3-coverage run tests/__init__.py
    - pylint3 -f html icetdev/ > .pylint_report.html
    - mkdir public
    - cp .pylint_report.html public/
    - cp .coverage public/
    - grep rated .pylint_report.html | awk '{print $7}' > public/.pylint_score    
  artifacts:
    paths:
      - public
    expire_in: 30 days 


